<a href="https://colab.research.google.com/github/btretto03/Studies-for-Real-Time-Emotion-Recognition/blob/main/studies/pytorch_studies/01_tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [27]:
import torch
import numpy as np

In [25]:
# Lists
list = [1, 2, 3, 4, 5]

In [28]:
# Numpy arrays
np1 = np.array(list)
np1

array([1, 2, 3, 4, 5])

In [29]:
# Tensor
tensor_2d = torch.randn(3,4)
tensor_2d

tensor([[ 2.6895, -0.6282, -1.7303,  1.3742],
        [-0.1044, -1.1838, -0.0340, -2.3592],
        [ 2.2167,  0.0221,  0.6178,  0.7323]])

In [30]:
tensor_3d = torch.zeros(2, 3, 4)
tensor_3d

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [32]:
## Create tensor our of numpy array
tensor_np = torch.tensor(list)
tensor_np

tensor([1, 2, 3, 4, 5])