<a href="https://colab.research.google.com/github/btretto03/Studies-for-Real-Time-Emotion-Recognition/blob/main/studies/pytorch_studies/02_tensors_operations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [33]:
import torch

In [34]:
my_torch = torch.arange(10)
my_torch

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [35]:
# Reshape and view
my_torch = my_torch.reshape(2, 5)
my_torch

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [36]:
# Reshape if we don't know the number of items using -1
my_torch2 = torch.arange(10)
my_torch2 = my_torch2.reshape(5,-1)
my_torch2

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])

In [37]:
# With reshape and view they will update
my_torch3 = torch.arange(10)
my_torch3

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [38]:
my_torch4 = my_torch3.reshape(2,5)
my_torch4

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [41]:
my_torch3[0] = 1982
my_torch3

tensor([1982,    1,    2,    3,    4,    5,    6,    7,    8,    9])

In [43]:
my_torch4 # it changes too

tensor([[1982,    1,    2,    3,    4],
        [   5,    6,    7,    8,    9]])

In [46]:
# Slices
my_torch5 = torch.arange(10)
my_torch5[7] # note it's not just 7 is tensor(7)

tensor(7)

In [48]:
# Grab slices
my_torch6 = my_torch5.reshape(5, 2)
my_torch6[:, 1]

tensor([1, 3, 5, 7, 9])