<a href="https://colab.research.google.com/github/btretto03/Studies-for-Real-Time-Emotion-Recognition/blob/main/studies/studies_Pytorch/03_tensors_math_operations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [88]:
import torch
import numpy as np

In [89]:
tensor_a = torch.tensor([1, 2, 3, 4])
tensor_b = torch.tensor([5, 6, 7, 8])

In [90]:
# Shorthand addition
tensor_a + tensor_b

tensor([ 6,  8, 10, 12])

In [91]:
# Longhand addition
add_long = torch.add(tensor_a, tensor_b)
add_long

tensor([ 6,  8, 10, 12])

In [92]:
# Shorthand subtraction
tensor_b - tensor_a

tensor([4, 4, 4, 4])

In [93]:
# Longhand subtraction
sub_long = torch.sub(tensor_b, tensor_a)
sub_long

tensor([4, 4, 4, 4])

In [94]:
# Shorthand multiplication
tensor_a * tensor_b

tensor([ 5, 12, 21, 32])

In [95]:
# Longhand multiplication
mul_long = torch.mul(tensor_a, tensor_b)
mul_long

tensor([ 5, 12, 21, 32])

In [96]:
# Shorthand division
tensor_b / tensor_a

tensor([5.0000, 3.0000, 2.3333, 2.0000])

In [97]:
# Longhand division
div_long = torch.div(tensor_b, tensor_a)
div_long

tensor([5.0000, 3.0000, 2.3333, 2.0000])

In [98]:
# Shorthand modulus
tensor_b % tensor_a

tensor([0, 0, 1, 0])

In [99]:
# Longhand remainder
mod_long = torch.remainder(tensor_b, tensor_a)
mod_long

tensor([0, 0, 1, 0])

In [100]:
# Longhand for powers (tensor_a to the power of tensor_b)
pow_long = torch.pow(tensor_a, tensor_b)
pow_long

tensor([    1,    64,  2187, 65536])

In [101]:
# Note that this creates a NEW tensor in memory and leaves tensor_a unchanged
tensor_a

tensor([1, 2, 3, 4])

In [102]:
# Using the underscore (_) at the end of the function
# This modifies tensor_a DIRECTLY and returns nothing or the modified tensor
tensor_a.add_(tensor_b)
tensor_a

tensor([ 6,  8, 10, 12])